# Generated by Django 2.1.7 on 2019-03-27 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='subtopics',
            fields=[
                ('subtopics_id', models.AutoField(primary_key=True, serialize=False)),
                ('subtopics_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='subtopics_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theory', models.CharField(max_length=50)),
                ('diagram', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('subtopics_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.subtopics')),
            ],
        ),
        migrations.CreateModel(
            name='topic',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=30)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.course')),
            ],
        ),
        migrations.AddField(
            model_name='subtopics',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.topic'),
        ),
    ]
