# Generated by Django 2.1.7 on 2019-04-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_auto_20190402_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_picture',
            field=models.ImageField(upload_to='courses/'),
        ),
    ]
