# Generated by Django 2.1.7 on 2019-04-10 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_auto_20190410_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=30)),
                ('teacher_email', models.EmailField(max_length=250)),
                ('teacher_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='teacher_allowance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.course')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.teacher')),
            ],
        ),
    ]
