# Generated by Django 2.1.7 on 2019-04-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0006_auto_20190410_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopics_info',
            name='code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='subtopics_info',
            name='diagram',
            field=models.ImageField(upload_to='diagram_representation/'),
        ),
        migrations.AlterField(
            model_name='subtopics_info',
            name='theory',
            field=models.TextField(),
        ),
    ]
