# Generated by Django 2.1.7 on 2019-04-17 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_auto_20190413_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtopics_info',
            old_name='code',
            new_name='code_py',
        ),
    ]
