# Generated by Django 2.1.7 on 2019-04-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0009_auto_20190417_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopics_info',
            name='code_cpp',
            field=models.TextField(default=None),
        ),
    ]
