# Generated by Django 2.1.7 on 2019-04-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0010_subtopics_info_code_cpp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopics_info',
            name='code_py',
            field=models.TextField(default=None),
        ),
    ]
